[build]
  publish = "dist/"
  command = "sed -i \"s|SITE_URL|${URL}|g\" netlify.toml && export API_URL=$URL/api && export SEARCH_URL=$SEARCH_URL && yarn && yarn setup && yarn build"

[context.deploy-preview]
  command = "sed -i \"s|SITE_URL|${DEPLOY_PRIME_URL}|g\" netlify.toml && export API_URL=$DEPLOY_PRIME_URL/api && export SEARCH_URL=$SEARCH_URL && yarn && yarn setup && yarn build"

[[redirects]]
  from = "/api/search"
  to = "https://stoic-galileo-1d5a50.netlify.app/.netlify/functions/search"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://stoic-galileo-1d5a50.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/feed/*"
  to = "https://stoic-galileo-1d5a50.netlify.app/feed/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/listeningparties/*"
  to = "/listening-parties/:splat"

[[redirects]]
  from = "/articles/some-spotify-and-the-strange-new-world-of-music-consumption"
  to = "/articles/soma-spotify-and-the-strange-new-world-of-music-consumption"

[[redirects]]
  from = "/reviews/adventures-of-a-reluctant-superhero-chali-2nakrafty-kuts"
  to = "/reviews/chali-2na-krafty-kuts-adventures-of-a-reluctant-superhero"

[[redirects]]
  from = "/reviews/review-heaven-upside-down-marilyn-manson"
  to = "/reviews/marilyn-manson-heaven-upside-down"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "SITE_URL"
