[build]
  publish = "build"
  command = "export SITE_URL=$URL && export EXT_API_URL=$PROD_API_URL && sed -i \"s|SITE_URL|${URL}|g\" netlify.toml && sed -i \"s|EXT_API_URL|${EXT_API_URL}|g\" _redirects && export API_URL=$SITE_URL/api && npm run build"

[context.deploy-preview]
  command = "export SITE_URL=$DEPLOY_PRIME_URL && export EXT_API_URL=$DP_API_URL && sed -i \"s|SITE_URL|${DEPLOY_PRIME_URL}|g\" netlify.toml && sed -i \"s|EXT_API_URL|${EXT_API_URL}|g\" _redirects && export API_URL=$SITE_URL/api && npm run build"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "SITE_URL"
