[build]
  publish = "dist/"
  command = "sed -i \"s|SITE_URL|${URL}|g\" netlify.toml && npm run build"
[build.environment]
  API_URL = "SITE_URL/api"

[[redirects]]
  from = "/api/*"
  to = "https://stoic-galileo-1d5a50.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "SITE_URL"
